; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_tutorial=music_data_tutorial
.endif

music_data_tutorial:
	.byte 1
	.word @instruments
	.word @samples-52
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	.byte .lobyte(@tempo_env_6_mid), .hibyte(@tempo_env_6_mid), 0, 0

.export music_data_tutorial
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env4,@env0,@env8,@env6
	.word @env12,@env0,@env8,@env6
	.word @env11,@env0,@env8,@env5
	.word @env3,@env0,@env1,@env5
	.word @env3,@env0,@env9,@env5
	.word @env2,@env10,@env7,@env6

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$0c,$0f,$40	;13 (BassDrum)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;14 
	.byte $03+.lobyte(FAMISTUDIO_DPCM_PTR),$30,$0f,$40	;15 (Snare)

@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $c1,$c0,$00,$01
@env2:
	.byte $00,$ca,$ca,$c7,$c6,$c6,$c5,$04,$c4,$c3,$c2,$c1,$05,$c0,$00,$0d
@env3:
	.byte $0a,$c6,$c6,$c7,$02,$c6,$03,$c5,$00,$07,$c5,$03,$c4,$03,$c3,$03,$c2,$03,$c1,$02,$c1,$00,$14
@env4:
	.byte $04,$cf,$7f,$00,$01
@env5:
	.byte $00,$c0,$1d,$c0,$c1,$c2,$c2,$c1,$c0,$bf,$be,$bd,$be,$bf,$c0,$00,$03
@env6:
	.byte $00,$c0,$7f,$00,$01
@env7:
	.byte $7f,$00,$00
@env8:
	.byte $c2,$7f,$00,$00
@env9:
	.byte $c0,$c1,$00,$01
@env10:
	.byte $c0,$c1,$03,$c2,$c1,$c2,$c1,$c2,$c1,$c2,$00,$09
@env11:
	.byte $00,$c5,$c6,$c7,$00,$03
@env12:
	.byte $08,$c8,$c7,$c6,$c5,$c4,$00,$05,$c4,$c3,$00,$09
@tempo_env_6_mid:
	.byte $03,$05,$80
@song0ch0:
	.byte $86, $36, $95, $39, $95, $3b, $95
@song0ch0loop:
	.byte $6a, .lobyte(@tempo_env_6_mid), .hibyte(@tempo_env_6_mid), $86, $3b, $ad, $3b, $ad, $3b, $95, $39, $ad, $3b, $ad, $39
	.byte $95, $3b, $95, $3d, $95, $3e, $ad, $40, $ad, $6b, $3e, $95, $3d, $ad, $3d, $ad, $3b, $ad, $3d, $f7, $ad, $f9, $ad, $6b
	.byte $3e, $c5, $3d, $c5, $3e, $ad, $3b, $f7, $ad, $f9, $95, $6b, $97, $36, $95, $39, $95, $3b, $95, $3d, $95, $3e, $95, $3d
	.byte $95, $3b, $95, $3d, $f7, $95, $f9, $ad, $6b, $84
@song0ref82:
	.byte $32, $ad, $62, $61, $fa, $32, $39, $ad, $62, $39, $f7, $f5, $36, $ad, $6b, $3b, $95, $3d, $ad, $3e, $f7, $f7, $c5, $6b
	.byte $ff, $11
	.word @song0ref82
	.byte $6b, $3e, $c5, $40, $c5, $3d, $ad, $3e, $c5, $3b, $c5, $39, $ad, $6b, $3b, $f7, $f7, $c5, $86, $36, $95, $39, $95, $3b
	.byte $95, $fd
	.word @song0ch0loop
@song0ch1:
	.byte $c7
@song0ch1loop:
	.byte $88, $32, $ad, $32, $ad, $32, $95, $31, $ad, $32, $ad, $31, $95, $32, $95, $34, $95, $36, $ad, $37, $ad, $36, $95, $34
	.byte $ad, $34, $ad, $32, $ad, $34, $f7, $ad, $f9, $ad, $36, $c5, $34, $c5, $36, $ad, $32, $f7, $ad, $f9, $95, $97, $2d, $95
	.byte $31, $95, $32, $95, $34, $95, $36, $95, $34, $95, $32, $95, $34, $f7, $95, $f9, $ad, $82
@song0ref205:
	.byte $2d, $8f, $f9, $83, $2f, $8f, $f9, $62, $2d, $81, $32, $8f, $f9, $62, $2f, $81, $2d, $8f, $f9, $62, $32, $81, $2f, $8f
	.byte $f9, $62, $2d, $81, $32, $8f, $f9, $62, $2f, $81, $2d, $8f, $f9, $62, $32, $81, $2f, $8f, $f9, $62, $2d, $81, $2d, $8f
	.byte $f9, $62, $2f, $81, $2f, $8f, $f9, $62, $2d, $81, $34, $8f, $f9, $62, $2f, $81, $2d, $8f, $f9, $62, $34, $81, $2f, $8f
	.byte $f9, $62, $2d, $81, $34, $8f, $f9, $62, $2f, $81, $2d, $8f, $f9, $62, $34, $81, $2f, $8f, $f9, $62, $2d, $81, $2a, $8f
	.byte $f9, $62, $2f, $81, $2f, $8f, $f9, $62, $2a, $81, $32, $8f, $f9, $62, $2f, $81, $2a, $8f, $f9, $62, $32, $81, $2f, $8f
	.byte $f9, $62, $2a, $81, $32, $8f, $f9, $62, $2f, $81, $2a, $8f, $f9, $62, $32, $81, $2f, $8f, $f9, $62, $2a, $81, $32, $8f
	.byte $f9, $62, $2f, $81, $36, $8f, $f9, $62, $32, $81, $3b, $8f, $f9, $62, $36, $81, $32, $8f, $f9, $62, $3b, $81, $36, $8f
	.byte $f9, $62, $32, $81, $3b, $8f, $f9, $62, $36, $81, $3e, $8f, $f9, $62, $3b, $81, $42, $8f, $f9, $62, $3e, $81
	.byte $ff, $9f
	.word @song0ref205
	.byte $ff, $9f
	.word @song0ref205
	.byte $fd
	.word @song0ch1loop
@song0ch2:
	.byte $c7
@song0ch2loop:
	.byte $80
@song0ref407:
	.byte $23, $93, $00, $23, $93, $00, $23, $93, $00, $23, $ab, $00, $1e, $93, $00, $23, $93, $00, $23, $93, $00
	.byte $ff, $15
	.word @song0ref407
@song0ref431:
	.byte $21, $93, $00, $21, $93, $00, $21, $93, $00, $21, $ab, $00, $28, $93, $00, $21, $93, $00, $21, $93, $00
	.byte $ff, $12
	.word @song0ref431
	.byte $26, $93, $00, $1f, $93, $00, $1f, $93, $00, $1f, $93, $00, $1f, $ab, $00, $1f
@song0ref471:
	.byte $93, $00, $1f, $93, $00, $1f, $93, $00, $1f, $93, $00, $1f, $93, $00, $1f, $93, $00, $1f, $ab, $00, $2a, $93, $00, $1f
	.byte $93, $00, $28, $93, $00, $1e, $93, $00, $1e, $93, $00, $1e, $93, $00, $1e, $ab, $00, $1e, $93, $00, $1e, $93, $00, $1e
	.byte $93, $00, $1e, $93, $00, $1e, $93, $00, $1e, $93, $00, $1e, $ab, $00, $25, $93, $00, $1e, $93, $00, $26
	.byte $ff, $12
	.word @song0ref471
@song0ref543:
	.byte $93, $00, $1f, $93, $00, $1f, $93, $00, $21, $93, $00, $21, $93, $00, $21, $93, $00, $21, $93, $00, $21, $93, $00, $21
	.byte $93, $00, $21, $93, $00, $21, $93, $00, $23, $93, $00, $23, $93, $00, $23, $93, $00, $23, $ab, $00, $23, $93, $00, $23
	.byte $93, $00, $23, $93, $00, $23, $93, $00, $23, $93, $00, $23, $93, $00, $25, $ab, $00, $26, $93, $00, $26, $93, $00, $61
	.byte $25, $26, $1f
	.byte $ff, $12
	.word @song0ref471
	.byte $ff, $48
	.word @song0ref543
	.byte $ff, $12
	.word @song0ref471
	.byte $ff, $48
	.word @song0ref543
	.byte $93, $00, $fd
	.word @song0ch2loop
@song0ch3:
	.byte $c7
@song0ch3loop:
	.byte $af, $8a
@song0ref639:
	.byte $2d, $95, $2d, $c5, $2d, $95, $2d, $c5, $2d, $95, $2d, $c5, $2d, $95, $2d, $95, $af
	.byte $ff, $11
	.word @song0ref639
	.byte $ff, $11
	.word @song0ref639
	.byte $ff, $10
	.word @song0ref639
@song0ref665:
	.byte $2d, $ad, $2d, $ad, $2d, $ad, $2d, $ad, $2d, $ad, $2d, $ad, $2d, $ad, $2d, $ad, $af
	.byte $ff, $10
	.word @song0ref639
	.byte $ff, $11
	.word @song0ref665
	.byte $ff, $11
	.word @song0ref639
	.byte $ff, $11
	.word @song0ref639
	.byte $ff, $10
	.word @song0ref639
	.byte $fd
	.word @song0ch3loop
@song0ch4:
	.byte $0d, $95, $0f, $95, $0f, $95
@song0ch4loop:
@song0ref707:
	.byte $0d, $95, $0d, $95, $0f, $95, $0d, $ad, $0d, $95, $0f, $95, $0d, $95, $0d, $95, $0d, $95, $0f, $95, $0d, $ad, $0d, $95
	.byte $0f, $95, $0d, $95
	.byte $ff, $1c
	.word @song0ref707
	.byte $ff, $1c
	.word @song0ref707
	.byte $ff, $1c
	.word @song0ref707
@song0ref744:
	.byte $0d, $ad, $0d, $ad, $0d, $ad, $0d, $ad, $0d, $ad, $0d, $ad, $0d, $ad, $0d, $ad
@song0ref760:
	.byte $0d, $95, $0d, $95, $0f, $95, $0f, $95, $0d, $95, $0d, $95, $0f, $95, $0f, $95
	.byte $ff, $10
	.word @song0ref760
	.byte $ff, $20
	.word @song0ref744
	.byte $ff, $10
	.word @song0ref760
	.byte $ff, $1c
	.word @song0ref707
	.byte $ff, $1c
	.word @song0ref707
	.byte $fd
	.word @song0ch4loop
